name: build

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'release/**'
  pull_request:
    branches:
      - 'main'
      - 'develop'
      - 'release/**'

jobs:
  build:
    strategy:
      matrix:
        version: ['7.4', '8.0', '8.1', '8.2']

    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Source checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.version }}
          coverage: xdebug

      - name: Cache PHP dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.OS }}-${{ matrix.version }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.version }}-composer-

      - name: Composer install
        run: composer install -o -n --prefer-dist

      - name: Create directories
        run: |
          mkdir tests-results
          mkdir tests-results/cache
          mkdir tests-results/infection
          mkdir tests-results/phpcs
          mkdir tests-results/phpmd
          mkdir tests-results/phpstan
          mkdir tests-results/phpunit

      - name: Run Code Sniffer
        run: composer phpcs

      - name: Run Mess Detector
        run: composer phpmd

      - name: Run PHPStan
        run: composer phpstan

      - name: Run PHPUnit
        run: composer phpunit

      - name: Run Infection
        run: composer infection

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: tests-results
          path: tests-results/
