name: build

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'release/**'
  pull_request:
    branches:
      - 'main'
      - 'develop'
      - 'release/**'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Source checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: xdebug

      - name: Cache PHP dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.OS }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Composer install
        run: composer install -o -n --prefer-dist

      - name: Create directories
        run: |
          mkdir tests-results
          mkdir tests-results/cache
          mkdir tests-results/infection
          mkdir tests-results/phpcs
          mkdir tests-results/phpmd
          mkdir tests-results/phpstan
          mkdir tests-results/phpunit

      - name: Run Code Sniffer
        run: vendor/bin/phpcs --report=junit --report-file=tests-results/phpcs/phpcs.xml src

      - name: Run Mess Detector
        run: vendor/bin/phpmd src xml phpmd.xml --ignore-violations-on-exit --report-file tests-results/phpmd/phpmd.xml

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --no-ansi --error-format=checkstyle > tests-results/phpstan/phpstan.xml

      - name: Run PHPUnit
        run: vendor/bin/phpunit

      - name: Run Infection
        run: vendor/bin/infection --coverage=tests-results/phpunit --min-msi=85 --min-covered-msi=95 --threads=4
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

      - name: Codecov
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}

      - name: Codacy
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh)
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: tests-results
          path: tests-results/
